config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'pages#index'
  get    'pages/no_privilege'   => 'pages#no_privilege'

  get     'login'             => 'sessions#login'
  post    'sessions/create'   => 'sessions#create'
  get     'logout'            => 'sessions#logout'

end

app/models/concerns/trim_before_validation.rb
# バリデーション前に全てのカラムの前後の空白を除去するコンサーン
#
# 使い方：
#
# class HogeModel < ActiveRecord::Base
#   include TrimBeforeValidation
# end
module TrimBeforeValidation extend ActiveSupport::Concern

  included do
    before_save :trim_before_validation
  end

  def trim_before_validation
    string_columns = self.class.columns.select { |column| column.type == :string }
    string_columns.each do |string_column| 
      attribute = string_column.name     
      value = send(attribute)        
      if value.present?          
        send("#{attribute}=", value.strip)        
      end      
    end      
    return true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id]) 
    end
  end

  def has_privilege(privilege)
    case privilege
    when :add_user
    when :always_false
      return false
    end
    return false
  end

  def check_privilege(privilege)
    if not has_privilege(privilege)
      redirect_to root_path, alert: "権限がありません"
      return false
    end
    return true
  end

  helper_method :current_user

  private

  def check_login
    if session[:user_id].blank?
      redirect_to login_path, alert: "ログインしてください"
    else
      @current_user = User.find(session[:user_id])
    end 
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :check_login

  def index
  end

  def login
    render :layout => 'login'
  end

  def error
  end

  def no_privilege
    return if check_privilege(:always_false) == false
    render :text => "OK"    # never reach here
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "login"
  before_action :check_login, except: [:login, :create, :logout]
  
  def login
  end

  def create
    email = params[:email]
    password = params[:password]

    # 認証をちゃんとやるには
    # rails g model user name:string password_digest:string
    #
    # # app/model/usres.rb
    # class User < ActiveRecord::Base 
    #   has_secure_password 
    # end 
    # 
    # # rails console
    # User.create!(:name => "admin", :password => "hoge", :password_confirmation => "hoge")
    #
    # http://qiita.com/regonn/items/4c76d4f3ef6c6af5c5e5
    
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "ログインしました"

      user.last_login = Time.now
      user.save!
    else
      redirect_to login_path, alert: "メールアドレスまたはパスワードが一致しません"
    end
  end 

  def logout
    session.delete(:user_id)
    redirect_to login_path, notice: "ログアウトしました"
  end 

  def test
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_login
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:id => :asc).page(params[:page]).per(20)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <!-- Bootstrap Core CSS -->
  <link href="/sb-admin2/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- MetisMenu CSS -->
  <link href="/sb-admin2/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">
  <!-- Custom CSS -->
  <link href="/sb-admin2/dist/css/sb-admin-2.css" rel="stylesheet">
  <!-- Custom Fonts -->
  <link href="/sb-admin2/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Bootstrap JS -->
  <script src="/sb-admin2/bower_components/bootstrap/dist/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><%= APP_TITLE %></a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
      <!-- /.dropdown -->
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-alerts">
          <li>
            <a href="#">
              <div>
                <i class="fa fa-comment fa-fw"></i> New Comment
                <span class="pull-right text-muted small">4 minutes ago</span>
              </div>
            </a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="#">
              <div>
                <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                <span class="pull-right text-muted small">12 minutes ago</span>
              </div>
            </a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="#">
              <div>
                <i class="fa fa-envelope fa-fw"></i> Message Sent
                <span class="pull-right text-muted small">4 minutes ago</span>
              </div>
            </a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="#">
              <div>
                <i class="fa fa-tasks fa-fw"></i> New Task
                <span class="pull-right text-muted small">4 minutes ago</span>
              </div>
            </a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="#">
              <div>
                <i class="fa fa-upload fa-fw"></i> Server Rebooted
                <span class="pull-right text-muted small">4 minutes ago</span>
              </div>
            </a>
          </li>
          <li class="divider"></li>
          <li>
            <a class="text-center" href="#">
              <strong>See All Alerts</strong>
              <i class="fa fa-angle-right"></i>
            </a>
          </li>
        </ul>
        <!-- /.dropdown-alerts -->
      </li>
      <!-- /.dropdown -->
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <%= current_user.name %> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
          <li><a href="<%= edit_user_path(current_user) %>"><i class="fa fa-user fa-fw"></i> アカウント</a>
          </li>
          <li><a href="#"><i class="fa fa-gear fa-fw"></i> 設定</a>
          </li>
          <li class="divider"></li>
          <li><a href="<%= logout_path%>"><i class="fa fa-sign-out fa-fw"></i>ログアウト</a></li>
        </ul>
        <!-- /.dropdown-user -->
      </li>
      <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
      <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
          <li class="sidebar-search">
            <div class="input-group custom-search-form">
              <input type="text" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
              <button class="btn btn-default" type="button">
                <i class="fa fa-search"></i>
              </button>
            </span>
            </div>
            <!-- /input-group -->
          </li>
          <li>
            <a href="/users"><i class="fa fa-table fa-fw"></i> ユーザー</a>
          </li>
          <li>
            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> サブメニュー<span class="fa arrow"></span></a>
            <ul class="nav nav-second-level">
              <li>
                <a href="#">サブ1</a>
              </li>
              <li>
                <a href="#">サブ2</a>
              </li>
            </ul>
            <!-- /.nav-second-level -->
          </li>
          <li>
            <a href="/pages/no_privilege"><i class="fa fa-lock fa-fw"></i> 権限なし</a>
          </li>
        </ul>
      </div>
      <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
  </nav>

  <div id="page-wrapper">
    <%= render :partial => "partials/notice" %>

    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= APP_TITLE  %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <%= csrf_meta_tags %>
</head>
<body class="login">


<div class="container">
  <%= yield %>
</div> <!-- /container -->

</body>
</html>

app/views/pages/error.html.erb
<% if (respond_to?(:alert) && alert.present?) || @alert.present? %>
  <p id="alert"><%= alert %><%= @alert %></p>
<% end %>

app/views/pages/index.html.erb
インデックス

app/views/partials/_notice.html.erb
    <% if respond_to?(:notice) && notice.present? %>
      <p class="notice">
        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
        <%= notice %>
      </p>
    <% end %>

    <% if (respond_to?(:alert) && alert.present?) || @alert.present? %>
      <p class="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <%= alert %><%= @alert %>
      </p>
    <% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label "名前" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label "メールアドレス" %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label "新しいパスワード" %><br>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label "パスワード（確認）" %><br>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "保存", class: "btn btn-primary" %>
    <%= link_to '戻る', users_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザーを編集</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<div class="index_actions">
  <%= link_to 'ユーザーを追加', new_user_path, class: 'btn btn-primary' %>
  <%= paginate(@users) %>
</div>

<table class="table table-condensed table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th>名前</th>
      <th>メールアドレス</th>
      <th>最終ログイン</th>
      <th>表示</th>
      <th>編集</th>
      <th>操作</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.last_login ? user.last_login.localtime.strftime('%Y-%m-%d %H:%M') : '' %></td>
        <td><%= link_to '表示', user %></td>
        <td><%= link_to '編集', edit_user_path(user) %></td>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              操作 <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to '削除', user, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %></li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<div class="index_actions">
  <%= link_to 'ユーザーを追加', new_user_path, class: 'btn btn-primary' %>
  <%= paginate(@users) %>
</div>

app/views/users/new.html.erb
<h1>ユーザーを追加</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>ユーザー</h1>

<p>
  <strong>名前:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>メールアドレス:</strong>
  <%= @user.email %>
</p>

<%= link_to '編集', edit_user_path(@user), class: "btn btn-primary" %>
<%= link_to '戻る', users_path , class: "btn btn-default"%>